### ISSUE TITLE
Which crate to use

### ISSUE THREAD

**Issue by divanvisagie** [arcnmx/nvapi-rs#7]
I have noticed that multiple crates on crates.io lead here and they each have slightly different apis. Which one is the correct one to use?

**Comment by OtaK** [comment]
* `nvapi-hi` is usually what you'd want to use as it takes care of most of the internals for you, and things make more sense
* `nvapi` is the middle ground, allows you to get a bit more dirty with the NVAPI and there are invariants that you *will* need to uphold as a developer otherwise crashing and/or unexpected behavior is expected
* `nvapi-sys` are direct bindings to the C++ NVAPI, you can do pretty much anything but you absolutely need to know what you're doing
